/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "DefaultEventTickets",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DefaultEventTickets__factory>;
    getContractFactory(
      name: "EventFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EventFactory__factory>;
    getContractFactory(
      name: "EventTickets",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EventTickets__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "DefaultEventTickets",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DefaultEventTickets>;
    getContractAt(
      name: "EventFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EventFactory>;
    getContractAt(
      name: "EventTickets",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EventTickets>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
